### ISSUE TITLE
Brite: Calculation on screen

### ISSUE THREAD

**Issue by DanMan32** [PlummersSoftwareLLC/NightDriverStrip#116]
**Problem**
Brite: section of display goes over 100% if it has to reduce the brightness to keep within the designated power.   I would think it would report the % reduced from originally designated brightness.

**Steps**
1. Set POWER_LIMIT_MW to low milliwatts in SPECTRUM section in globals.h
2.  Build and upload SPECTRUM project to controller
3.  Observer Brite: in controller display.   Shows over 100% when power is cut back
Should be under 100% indicating how much the power has been reduced from normal

**Example**
If you have the power limit set to 5000mW but the power required for set brightness at 255 would be 10,000mW, power control would cut the brightness probably to around 127.   Brite: would display 200%.   It should instead display 50% in that the LED brightness was cut in half.

**Notes**
Problem seems to be how the % is calculated in screen.cpp:
255.0f * 100 / calculate_max_brightness_for_power_mW(g_Brightness, POWER_LIMIT_MW));

calculate_max_brightness_for_power_mW returns the cut back brightness level from 1-255.   So, the calculation should be in the numerator, and the base amount in the denominator:
calculate_max_brightness_for_power_mW(g_Brightness, POWER_LIMIT_MW))*100/255.0f ;

This unless the intent of the Brite: value was to show the % overage in brightness setting to maintain power limits but I would think it more meaningful to show how much the brightness was automatically cut back rather than how much overage the set brightness is to what it was cut back.  

Since the user might be intentionally setting a lower brightness than maximum to begin with, and is required for the calculation function, might also be good to make the change based on what the target brightness is as set by g_Brightness rather than a fixed value of 255:
calculate_max_brightness_for_power_mW(g_Brightness, POWER_LIMIT_MW))*100/g_Brightness;

Not sure if g_Brightness would need a qualifier to make it as a float for the division.

**Comment by rbergen** [comment]
Fixed in commits 1ad6c144881903a10933dbb8fed743b9dc8270ff and 77eecb89f05e2be514e42aa8d917b1f4ef687549.
