### ISSUE TITLE
Move the g_ audio variables from global scope to an audio singleton class

### ISSUE THREAD

**Issue by davepl** [PlummersSoftwareLLC/NightDriverStrip#197]
## Move globals to a singletoon

These variables are in global scope:

extern float gScaler;                     // Instantaneous read of LED display vertical scaling
extern float gLogScale;                   // How exponential the peaks are made to be
extern volatile float gVURatio;           // Current VU as a ratio to its recent min and max
extern volatile float gVURatioFade;
extern volatile float gVU;                // Instantaneous read of VU value
extern volatile float gPeakVU;            // How high our peak VU scale is in live mode
extern volatile float gMinVU;             // How low our peak VU scale is in live mode
extern volatile unsigned long g_cSamples; // Total number of samples successfully collected
extern int g_AudioFPS;                    // Framerate of the audio sampler
extern unsigned long g_lastPeak1Time[NUM_BANDS];
extern float g_peak1Decay[NUM_BANDS];
extern float g_peak2Decay[NUM_BANDS];
extern float g_peak1DecayRate;
extern float g_peak2DecayRate;

They should be moved to an AudioStats class, made into a singleton, and then perhaps references by the AudioAnalyzer as a member rather than a big old set of globals.

Global variables are bad

Look in globals.h

**Example**
Feel free to repeat in other areas until we've NICELY cleaned up all globals in a readable way.

**Notes**

**Comment by rbergen** [comment]
Audio globals have been addressed with commit [fb18763894b6c05a2f806a19b50d1bc688ca6ffd](https://github.com/PlummersSoftwareLLC/NightDriverStrip/commit/fb18763894b6c05a2f806a19b50d1bc688ca6ffd), and commits that follow it.
