### ISSUE TITLE
Missing tomorrow forecast

### ISSUE THREAD

**Issue by davepl** [PlummersSoftwareLLC/NightDriverStrip#268]
## Bug report
Often times I get today's weather but tomorrow's stays all zeros.  They're separate, but not sure why one would succeed and the other would fail!

When it happens, I get the local town, temp, and today's conditions icon and the high and low for today.  For tomorrow, just zeros.

**Comment by rbergen** [comment]
I apologize for the painfully obvious question, but did you happen to catch any logging when this happens? I think I remember this happening when the board time was off (due to NTP synchronization not working), but I'm not entirely sure.

**Comment by davepl** [comment]
No, I didn't see anything remarkable in the logs... but it seems to have been resolved.  If it recurs, I'll re-open!
