### ISSUE TITLE
REGRESSION: OTA updates not functioning with expanded partition table

### ISSUE THREAD

**Issue by davepl** [PlummersSoftwareLLC/NightDriverStrip#28]
**Problem**
The code contains OTA support that worked when the project was small enough to fit in the default partition table.  When the code grew, partitions_custom.csv was added to accommodate it.   Unfortunately doing so seems to have broken OTA support.

**Steps**

1. Build the SPECTRUM config, ensure ENABLE_OTA is on 
2.  Run it, note IP, set upload_port to it, upload
3.  Note that it connects but the OTA code bails internally when checking the partition table.  That's as far as I debugged.

**Comment by BeldrothTheGold** [comment]
Oh, it looks like it might not be necessary to have a factory app. This might work? 

```
# ESP-IDF Partition Table
# Name,   Type, SubType,     Offset,      Size, Flags

nvs,        data,   nvs,     0x9000,    0x5000,
otadata,    data,   ota,     0xe000,    0x2000,
app0,       app,    ota_0,   0x10000,   0x150000,
app1,       app,    ota_1,   0x160000,  0x150000,
storage,    data,   spiffs,  0x330000,  0xF0000,   # for  4 MB
```

**Comment by davepl** [comment]
I thought it was tested and working before it was checked in!  We only verify that it BUILDS.  I suppose given an ESP32 emulator… no, never mind.

It’s important to test any changes, as the pull requests get a code review and a buddy build but not a runtime test.

- Dave

**Comment by BeldrothTheGold** [comment]
This seems to be resolved. I am no longer seeing crashes during OTA upload of the spectrum project.

**Comment by rbergen** [comment]
Closing this as it was marked resolved over a year ago.
