### ISSUE TITLE
Feature: Sports Scores

### ISSUE THREAD

**Issue by davepl** [PlummersSoftwareLLC/NightDriverStrip#290]
It would be nice to have an effect that cycled through the major game scores in a particular sport, like NFL/NBA/etc.   Should be cool and sexy and even animated if you're adventurous.  As with weather, you'd need to provide a setting for the API key as well as which sport to report on.

Bonus points for team logos :-)

**Comment by rbergen** [comment]
Closing, because superseded by #342.
