### ISSUE TITLE
UI: UI Comes up blank

### ISSUE THREAD

**Issue by davepl** [PlummersSoftwareLLC/NightDriverStrip#303]
When I launch a browser and go to the mesmerizer IP, I get the admin control panel but I don't really see anything until I click on the home button.  It should default to showing the effect list.

**Comment by MPMcIntyre** [comment]
Hi Dave, could you possibly provide a screen shot of the browser console (F12 to open the console in your browser, then F5 to refresh the page), it might give an indication of the error. I think it has to do with not defering the react script tag.

**Comment by rbergen** [comment]
@MPMcIntyre I don't think there's an error (or at least, my console doesn't show any), it's just how the UI currently works.

What the issue raises is that the web UI comes up like this when you load it:
![web UI](https://github.com/PlummersSoftwareLLC/NightDriverStrip/assets/10425218/ca6a0953-932a-42ad-87a1-6994656b2d89)

That is: the page loads and the navigation controls are there, but the majority of screen real estate is empty. 

What I think Dave would like is the effect tiles to be shown straight away, which now requires a click on the home icon at the left:
![effect tiles shown](https://github.com/PlummersSoftwareLLC/NightDriverStrip/assets/10425218/c82cb197-3a8e-48e0-b394-1894cb2dd43a)

(Actually, Dave is also suggesting in #301 to change the tiles to a more list-like format, but that's a different issue.)

I hope this clarifies the issue somewhat?

**Comment by MPMcIntyre** [comment]
@rbergen Ah okay, yes that clarifies it thanks!

**Comment by davepl** [comment]
Hope this is what you’re looking for:

￼

**Comment by Louis-Riel** [comment]
A big change to the UI is coming soon. This next PR will a solid base to continue building the site on. This will include a migration to typescript, upgraded build system, and a re-giggying of the UI.

We have alot of UI design work to do, which will include the screw flow, and the look. We need help with good designers with that human touch. 

I will try to push something over the weekend, that will probably not yet include the typescript migration, just the reworked UI, for folks to get thinking about cool design ideas

**Comment by Louis-Riel** [comment]
The effect list is now displayed by default when opening the page.

**Comment by Louis-Riel** [comment]
![image](https://github.com/PlummersSoftwareLLC/NightDriverStrip/assets/53452394/333fbb26-01a7-4ca6-81ce-ba9be4b679d7)

**Comment by davepl** [comment]
Fixed in the latest build I tried from Louis!
