### ISSUE TITLE
Servers listening for external incoming connections mostly failing

### ISSUE THREAD

**Issue by robertlipe** [PlummersSoftwareLLC/NightDriverStrip#322]
## Bug report
I think the diagnostics point to leaving the tracks here, but the cause may be higher:

(I) (ConnectToWiFi)(C0) Starting/restarting Socket Server...
(W) (ProcessIncomingConnectionsLoop)(C1) Error accepting data!
I) (ConnectToWiFi)(C0) Socket server started.

**Problem**
Inbound network connection attempts on ports 443 and 80 fail, even i you just do a 'telnet whatever 80". Once things are out of sync, even the telnet connection dies.

telnet 192.168.2.165 23 # works
telnet to ports 80 and 443 fail:
➜  nightdriverstrip git:(msg_cleanup) ✗ telnet 192.168.2.165 80
Trying 192.168.2.165...
telnet: connect to address 192.168.2.165: Connection refused
telnet: Unable to connect to remote host
➜  nightdriverstrip git:(msg_cleanup) ✗ telnet 192.168.2.165 443
Trying 192.168.2.165...
telnet: connect to address 192.168.2.165: Connection refused
telnet: Unable to connect to remote host

**Steps**

1.  Build 'mesmerizer' target on mesmerizer hardware. (Hosted on MacOS/risc-v, but I sure hope that doesn't matter.)
2.  Observe logs. In my case, via "sudo cu -s 115200 -l /dev/cu.usbserial-101"
3.  Look enviously at various discussions with screen shots of web interface and feel envy. (OK, and desire to use other debugging features over sockets.)
4. The telnet interface, but the app-specific sockets running the internal daemons are failing, as confirmed via nmap.

**Example**

**Notes**

The socket code seems very textbook. I don't know if it's something special about my environment (maybe reverse DNS looks don't work, for example), if this is broken for a large group of people, or my expectations are off.

Commented system logs, coming fresh out of a reboot:

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13192
load:0x40080400,len:3028
entry 0x400805e4
**E (1157) esp_core_dump_flash: No core dump partition found!
E (1157) esp_core_dump_flas���r��ɕ�"յ�����ѥѥ���2�չ��jR�Replacing Idle Tasks with TaskManager...**
               (I) (PrintOutputHeader)(C1) NightDriverStrip
_That seems unfortunate, but I don't think is related._

(I) (PrintOutputHeader)(C1) M5STICKC: 0, USE_M5DISPLAY: 0, USE_OLED: 0, USE_TFTSPI: 0, USE_LCD: 0, USE_AUDIO: 1, ENABLE_REMOTE: 1
(I) (PrintOutputHeader)(C1) ESP32 PSRAM Init: OK

Default configs, I think.

(I) (PrintOutputHeader)(C1) Version 36: Wifi SSID: "ElderOfTheInternet" - ESP32 Free Memory: 257948, PSRAM:4192043, PSRAM Free: 4178867
(I) (PrintOutputHeader)(C1) ESP32 Clock Freq : 240 MHz
(I) (setup)(C1) Startup!
(I) (setup)(C1) Starting DebugLoopTaskEntry

This is a little misleading. This isn't the SSID we've found, it's the SSID we want. But carrying on.

(W) (DeviceConfig)(C1) DeviceConfig could not be loaded from JSON, using defaults

DeviceConfig is demand created, right? It's interesting that one from a previous run didn't persist.

(I) (ConnectToWiFi)(C0) Setting host name to NightDriverStrip...**WL_NO_SHIELD**

That can't be good, but it's not clear what error 255 is or really, where it came from. (Man, I'm going to have to tackle JTAG debugging on this thing...)

(W) (ConnectToWiFi)(C0) Pass 1 of 5: Connecting to Wifi SSID: "ElderOfTheInternet" - ESP32 Free Memory: 110008, PSRAM:4175803, PSRAM Free: 1013543

So on the first iteration, we see our AP (that's mine) and I've confirmed that it's authenticated correctly.  We have a bunch of memory for now.

(W) (LoadJSONFile)(C1) Out of memory reading JSON from file /effects.cfg - increasing buffer to 6909 bytes

It's hard to tell, but I think it's just bragging that this was an initial allocation to demand fill a buffer. "Good job"

(W) (ColorDataTaskEntry)(C1) Started color data server!
(W) (ConnectToWiFi)(C0) Connected to AP with BSSID: 74:AC:B9:4E:6A:40
(W)
(W) (ConnectToWiFi)(C0) Received IP: 192.168.ZZ.ZZ

Yay. But next it turns ugly:

(I) (ConnectToWiFi)(C0) SetionsLoop)(C1) ErrorW) (ProcessIncomingConnectionsLoop)(C1) Error accepting data!
(W) (SocketServerTaskEntry)(C1) Socket connection closed.  Retrying...
[  6232][E][WiFiUdp.cpp:221] parsePacket(): could not receive data: 9
(W)
(W) (StartEffectThread)(C1) >> Launching Subs Effect Thread
(W) (StartEffectThread)(C1) >> Launching Weather Effect Thread
(W) (NotifyJSONWriterThread)(C1) >> Notifying JSON Writer Thread
(I) (ConnectToWiFi)(C0) Starting Web Server...
(I) (begin)(C0) Connecting Web Endpoints

(I) (begin)(C0) Embedded html file size: 1350
(I) (begin)(C0) Embedded jsx file size: 39948
(I) (begin)(C0) Embedded ico file size: 15406
(I) (begin)(C0) Embedded timezones file size: 17834
[  6984][E][AsyncTCP.cpp:1251] begin(): failed to start task
(I) (begin)(C0) HTTP server started
(I) (ConnectToWiFi)(C0) Web Server begin called!

Now things are just failing to taunt us. The servers seem to have started, but if we connect directly, the accepts all just fall apart.

Is this stuff working for anyone? Am I misunderstanding the expectation that I should be able to open a browser (maybe even https - I can't tell if there's a cert smuggled in there)  on http://NightDriverStrip and have reasonable access to pointy clickity things?

I'm willing to chase things up into the IDF/Arduino layers if I HAVE to, but first I'd like confirmation that my basic expectations are correct and that this is working for someone...

**Comment by rbergen** [comment]
To the extent the issue concerns port 80, this is a known problem in the current version of Mesmerizer. The reason is that the device has insufficient memory left to start the web server (that being an instance of `CWebServer`).
I've opened #321 to fix this.

Port 443 will never be open, as nothing listens to it; the webserver does not implement TLS.

**Comment by rbergen** [comment]
With the changes of #321 now in, the webserver should start again, and hence the web UI should load from http://<device IP>:80
I know it does for Dave and me, at least. :)

**Comment by rbergen** [comment]
You're welcome! Thanks for reporting your findings with the updated version of the codebase, and glad to see you got some key networking things going at least.

About the memory: the core RAM that we now have ~104K left of is (only) 520K in total. The 4M is PSRAM that can be used for certain things, but not others. We've set up Mesmerizer to allocate everything over 128 bytes in PSRAM, but that still leaves quite a few smaller things that are quite inevitably allocated on "plain heap". On top of that, all stacks - every task has one - are also allocated in regular RAM by definition.
