### ISSUE TITLE
Work Item: Partition table

### ISSUE THREAD

**Issue by davepl** [PlummersSoftwareLLC/NightDriverStrip#323]
The chip we're using on the Mesmerizer has 8GB of PSRAM and 8GB of flash (or more, depending on which chip you have).  But our partition table only works for 4GB.  I've tried to create an 8GB version but can't set it to boot, so need someone to take a look!

Two main goals:
1) Enable OTA by creating the two APP partitions and then re-enable ENABLE_OTA for mesmerizer
2) Get access to all 8GB of PSRAM if possible (could be the Arduino version doesn't handle it, but can't prove it)

**Comment by davepl** [comment]
So far the target has been to allocate up to 500 frames of buffer.  If PSRAM were tight, it could be less, but since it’s abundant… 500.  And then we allocate most everything we can from PSRAM preferentially to use it up first.  

There are a couple of places, like decompression, where I copy to a RAM buffer first because the process is random access which is slow over SPIRAM.  But so far, everything runs well using PSRAM.

There’s a RESERVE_MEMORY setting in the builds as well.  If USE_PSRAM is NOT defined, that’s how much RAM will be left aside during buffer allocation.  If USE_PSRAM is defined, it’s how much PSRAM will be preserved.

The most pressing issue though would be to figure out why we can’t seem to partition the larger flash in such a way as to take advantage of it.  So far I’ve been unable to get it to boot with anything other than 4GB partition max.  But for all I know the Arduino version of the espressif code might assume it, I don’t know!

 Dave

**Comment by rbergen** [comment]
Completed by #346.
