### ISSUE TITLE
Easy Bug to Fix: Pulsar effect

### ISSUE THREAD

**Issue by davepl** [PlummersSoftwareLLC/NightDriverStrip#334]
The pulsar effect is supposed to, and used to, display little blooming stars that get to be about 16 pixels wide.  Right now they're enormous, extend outside the screen, and crash the system.

Basics:  Fix Pulsar!

**Comment by davepl** [comment]
I’m of the opinion that if it draws outside the bounds, we should catch that case and throw a fatal exception, and the effect should get fixed.  The alternatives seem to be eating the pixel and hiding the bug or letting I corrupt… so that’s my though!

**Comment by davepl** [comment]
For debugging you need to put jumpers across the 4-5 pairs of jumper pins that are marked as TDI,TDO, and so on.  Then PlatformIO should be able to debug with odd.

The mesmerizer board presents TWO serial ports, one for debugging and one for serial logging.  On the PC, at least, you have to change the driver on one of them with Zadig.


https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/jtag-debugging/configure-ft2232h-jtag.html￼

I believe the checking of the pixel and the throwing of the exception should happen at the lowest level (setPixel?) wherever it’s about to write to the LED buffer. 

- Dave

**Comment by davepl** [comment]
Yes, you should be able to get away with Dupont connectors!  Cool about the S3, I’ll have to try it!

I have a big pull bottle of 2.00 and 2.54mm now, because the little ones are hard to find!

My guess is that the effect in question has a sound-based amplitude, and that my recent changes to make audio broke it, and I just never happened to display that effect for very long!

- Dave

**Comment by davepl** [comment]
Just a heads-up:  I’m adding low level exception code to throw if you try to access invalid pixels.  I’ve already founds bugs in a few effects, and am fixing as I go!

- Dave

**Comment by davepl** [comment]
Wow, there were a LOT of broken effects writing out of range.  Wonder where they were writing before!  

In any event, I added the safeguard code and for now just debug warn if you draw out of range, will make it more hardcore soon.  I fixed the 10 or so effects that triggered it.

- Dave

**Comment by davepl** [comment]
Glad you brought it to the surface!  Based on the effects I fixed (most of which were inherited from Aurora) there were lots of places where it was overwriting. I can’t believe we survived the corruption, frankly!

- Dave

**Comment by davepl** [comment]
The fundamental difference seems to be a presumption that drawPixel() is allowed to attempt to draw outside its bounds, and it’s caught there.  We could certainly adopt that approach, or even enable it later if we like, but for now I think it hides bugs if we let it eat pixels so for now I prefer that all drawPixel calls be valid.

If it winds up cramping anyone’s style, I can remove the exception and replace it with a bounds check that discards.

- Dave

**Comment by rbergen** [comment]
Fixed by #345
