### ISSUE TITLE
BUG: AudioGraph bars all at the same level

### ISSUE THREAD

**Issue by davepl** [PlummersSoftwareLLC/NightDriverStrip#348]
## Bug report
After about 30 minutes of running (might require less), the audiograph effect has the same level for all the bars.  

Changing away and back doesn't always fix it.

Changing to the Spectrum effect and then coming back to the Audiograph effect "fixes" it.

**Comment by davepl** [comment]
What's weird is that stepping forward to the Spectrum effect and then back to Audiograph fixes it. So I wonder if AudioGraph needs to set peakDecayRate1 and 2 like the SpectrumAnalyzer effect does in Start()?

**Comment by davepl** [comment]
I think I've fixed it.  The SpectrumBarEffect needed to set the global audio decay rates, which the spectrum effect did, but the spectrumbar effect did not.

**Comment by rbergen** [comment]
Nice! Can I contribute to verifying this has indeed been fixed? If so, what branch should I check out and flash?

**Comment by rbergen** [comment]
Fixed by #386.
