### ISSUE TITLE
BUG: LEDSTRIP project doesn't allow WiFi credentials to be set via Improv

### ISSUE THREAD

**Issue by rbergen** [PlummersSoftwareLLC/NightDriverStrip#371]
### Problem

The LEDSTRIP project demands WiFi to be connected (`WAIT_FOR_WIFI` is defined as 1), and bails out by rebooting if it isn't. This is handled by [lines 629 to 637 in main.cpp](https://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/src/main.cpp#L629-L637).
If no WiFi credentials are available at boot, the code in [lines 224 to 228 in network.cpp](https://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/src/network.cpp#L224-L228) immediately gives up on WiFi connectivity, leading to the device rebooting very early in the boot process.

Although this makes sense if the project is flashed using a method that requires WiFi credentials to be set in secrets.h, it creates a problem if the project is flashed using the web installer, Part of that workflow is the setting of WiFi credentials using Improv. For the LEDSTRIP project that's impossible because the device is stuck in a boot loop by the time the user has a chance to enter their WiFi credentials.

### Solution

If `WAIT_FOR_WIFI` is set to 1, the device should allow enough time for the user to enter WiFi credentials.

### Note

This problem was first reported in issue #367. I'm opening this specific issue at @davepl's request.

**Comment by davepl** [comment]
In deployment, a chip that comes up and fails to get wifi is useless and has to be manually reset.  That’s why in the code it tries some reasonable number of times, like 10, and then reboots.

It’s done this way because the majority of times, failure to get wifi is transient and can be fixed with a reboot.  But if you just kept trying, it’d never work.

I don’t want to get on too many ladders, so OTA updates and automatic resets are a passionate topic for me :-). I’ve got a lot of the LEDSTRIP project scattered around here!

- Dave

**Comment by davepl** [comment]
But a blinking pattern would tell me:

“Dave, this module won’t connect to WiFi this power cycle.  Please climb a ladder to reset the chip.”  That’s fine on the bench but not in production.

If you can get a WiFi module into this state and then get it OUT without a reboot through successful backoff, that would be a better solution, and I encourage you to implement it.

For now, my suspicion is that only a reboot will correct it.  I don’t know enough about the internal wifi espressif code to know why, though!

 -Dave

**Comment by sdmtr** [comment]
The core problem as described in the bug report is that a reboot definitively cannot correct a situation in which wifi credentials haven't been supplied, which will always be the case when flashing LEDSTRIP from the web installer. There isn't enough time between the board booting and rebooting for the web installer to ask the user to supply credentials and then send them through to the board, so no matter what, anyone who tries to install LEDSTRIP from the web installer will never, ever be able to use their board, and they'll have no idea why unless they inspect the console output and put two and two together.

**Comment by rbergen** [comment]
I've opened #395 to fix this.
