### ISSUE TITLE
Remote misses entries depending on direction

### ISSUE THREAD

**Issue by robertlipe** [PlummersSoftwareLLC/NightDriverStrip#408]
Beating on the remote effect up and down keys, sometimes entries are missed.

## Bug report
I've noticed this in the larger project, but it's easier to repro with a tiny entries table. (I may also have 'up' and 'down' misdefined in this discussion.) I think there's an off by one or a >/>= type issue somewhere.

(Yes, I could go find it, but I wanted to write this down and stay focused. It's a good starter project for incomers.)

**Steps**

1.  Beat on the up/down key. Observe that you can traverse the entire effect list.
2.  Beat on the down/up key (the opposite of that one) Observe that you can never get the LAST entry in the table on screen.
3.  

**Example**
In my simplified case, my entire effects table is:
        ADD_EFFECT(EFFECT_MATRIX_SMNOISE,       PatternSMNoise);
        ADD_EFFECT(EFFECT_MATRIX_SMNOISE,       PatternSMNoise, "Lava Rainbow", PatternSMNoise::EffectType::LavaLampRainbow_t);
        ADD_EFFECT(EFFECT_MATRIX_SMNOISE,       PatternSMNoise, "Lava Rainbow Stripe", PatternSMNoise::EffectType::LavaLampRainbowStripe_t);
        ADD_EFFECT(EFFECT_MATRIX_SMNOISE,       PatternSMNoise, "Shikon", PatternSMNoise::EffectType::Shikon_t);
        ADD_EFFECT(EFFECT_MATRIX_SMNOISE,       PatternSMNoise, "ColorCube", PatternSMNoise::EffectType::ColorCube_t);
        ADD_EFFECT(EFFECT_MATRIX_SMPRISMATA, PatternSMPrismata);
        
        If I press the key labeled down (the key second from the left) on my 44 key, it moves UP this table and wraps around from Lava Lamp (whose name is in effects.cc and not here) to Color Cube.
        If I press the key labeled up (upper left corner) , it goes from Cube to Prismata and back to Lava Lamp.
        
        Pressing the down key, you can never get to Prismata. Ever.
        
        
**Notes**
I've observed with with both 24 and 44 key remotes. It's not the remote.

I'm suspicious of PreviousEffect()

            if (_iCurrentEffect == 0)
                _iCurrentEffect = EffectCount() - 1;

            _iCurrentEffect--;

Testing for the wraparound case BEFORE the decrement seems odd. But it's the LAST entry in the table that's unnavigable.

Needs attention.

**Comment by rbergen** [comment]
If that's the actual code then the bug is indeed obvious. It should look like this:

```cpp
        if (_iCurrentEffect == 0)
            _iCurrentEffect = EffectCount();

        _iCurrentEffect--;
```

If one wants to confirm it's not the remote, then one could perform a plain GET of http://&lt;device ip&gt;/previousEffect - or hit the "previous effect" button in the existing web UI. That also uses PreviousEffect().
