### ISSUE TITLE
Call to WriteWiFiConfig Parameters Need Swapping

### ISSUE THREAD

**Issue by kriztioan** [PlummersSoftwareLLC/NightDriverStrip#480]
Parameters to `WriteWiFiConfig` call need to be swapped.

https://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/8df4f2691130b185fbc71e226a6c4f635327f8b6/src/main.cpp#L335

**Comment by rbergen** [comment]
@kriztioan You're right. Good catch, thanks for reporting this. I've opened #481 to correct this.
