### ISSUE TITLE
Web UI: allow user to reset the device config, reset the effect list and/or reboot the device

### ISSUE THREAD

**Issue by rbergen** [PlummersSoftwareLLC/NightDriverStrip#482]
The on-board API's `/reset` endpoint allows three types of "reset" to be triggered:

- A reboot of the device (`board=true`)
- A reset-to-defaults of the device configuration (`deviceConfig=true`), which should always be combined with a device reboot
- A reset-to-default of the effect list (`effectsConfig=true`), which should always be combined with a device reboot

So far, the UI does not offer a facility to trigger the latter two. A board reset can be triggered by opening the global settings dialog and clicking "Apply and reboot device" without changing any settings, but I think that's not very intuitive.

I think the web UI should allow a user to trigger each of the three resets, as an independent action. Because of the impact of the latter two, a confirmation flow should probably be triggered before actually applying the resets in question. When it comes to location, the global settings dialog does seem to be a logical place to me. Exactly how to embed it into that dialog's design is something I'm not exactly sure of, which also means I don't have a strong opinion about it, up-front.

**Comment by KeiranHines** [comment]
One other idea would be to add an icon to the sidebar for, in that menu/dialog have reset controls. 
![image](https://github.com/PlummersSoftwareLLC/NightDriverStrip/assets/2768974/669c4bc1-0c56-42f7-96ec-06b4af6ee951)

**Comment by rbergen** [comment]
You know what, that's also fine by me! :)
