### ISSUE TITLE
Smoke Broken!

### ISSUE THREAD

**Issue by davepl** [PlummersSoftwareLLC/NightDriverStrip#486]
Looks like a recent change has broken the noise effect of Smoke.  It's now all sparkly on the leading edges, and looks broken compared to what it used to, where it was a smooth smoke edge.

**Comment by rbergen** [comment]
@davepl It's either what you say or PR #450. If it's the latter that means the change was deliberate based on the opinion of @robertlipe and myself that this is actually a better look for the effect than the previous one. 

@robertlipe Could you maybe check if the look of SMSmoke as the current code produces it, is indeed what I merged on September 30th?

**Comment by rbergen** [comment]
@robertlipe I've had some out-of-band communication with Dave about this, and he has a strong preference to revert to a smooth operation of SMSmoke, so without the sparkles. If we can do that while keeping the rolling black bar out of the equation, then I think we're still in a better place than we were before #450.

Is this something you can look into?
