### ISSUE TITLE
Web UI: improve rendering of setting editors

### ISSUE THREAD

**Issue by rbergen** [PlummersSoftwareLLC/NightDriverStrip#504]
While working on #503 I noticed a couple of things that I think we need to improve about the way setting editors are rendered in the global and effect setting dialogs. Specifically:

1. The name/label of a setting now seems to be rendered using the exact same font, including size and color, as the setting description. Particularly with combinations of setting editors that are not textual, this can make it difficult to distinguish one setting from the next. I think the setting names/labels should be made to stand out a little more. Whether this should be done using a bigger font, brighter color, text decorations or something else altogether, I'll leave to someone with actual UI design skills.
2. For Boolean/checkbox settings, the setting description is not shown and as such completely inaccessible. I think we should somehow make the description for these settings visible or accessible also. As with the other point, I'm not sure how to best do this.

**Comment by KeiranHines** [comment]
Thanks for the feedback. Checkbox settings is easy enough
![image](https://github.com/PlummersSoftwareLLC/NightDriverStrip/assets/2768974/e75e6ba2-3cda-46b6-883f-90847e815e57)
As for names/labels. Hows about this? 
![image](https://github.com/PlummersSoftwareLLC/NightDriverStrip/assets/2768974/facbb3fa-ada5-4e38-89ea-4660dec7fbbc)
![image](https://github.com/PlummersSoftwareLLC/NightDriverStrip/assets/2768974/404f07c0-25ba-4019-921a-486253463449)
I have changed the names/labels to be more consistent and slightly bigger. I have also re-positioned description for the checkbox although I am less sure about that idea.

**Comment by KeiranHines** [comment]
Alternatively with a less padding around the inputs
![image](https://github.com/PlummersSoftwareLLC/NightDriverStrip/assets/2768974/79745812-e667-4878-8d6e-1c875af440d1)
And with a background to the inputs
![image](https://github.com/PlummersSoftwareLLC/NightDriverStrip/assets/2768974/96efeb08-ccba-4e90-94b7-6541cb967d3a)

**Comment by rbergen** [comment]
@KeiranHines Thanks for the designs!

In my opinion:

- Adding checkbox setting descriptions underneath the checkbox control + label works best (i.e., as shown in your first screen snippet). 
- I think the change in label format helps, but maybe we should also add a little more whitespace between the individual settings (as in "above" the labels). 
- I don't think adding a background colour to the input fields adds much. It's actually mainly with the non-input field controls (sliders, colour pickers, etc.) that things get a bit "cramped" at the moment.
