### ISSUE TITLE
Update from M5Core2 to M5Unified

### ISSUE THREAD

**Issue by davepl** [PlummersSoftwareLLC/NightDriverStrip#582]
It looks like all of the M5 support has been unified into a single library, and the old individual stuff for the M5 Stick / Stack/ Plus/ Core2/ etc will go away.

Someone should move us to the unified lib!

**Comment by prschguy1** [comment]
hmmm, have looked at that a bit. It doesn't seem to be a very easy task. Would like to see that work though as I want to see M5Stack-s3 work here. Haven't tried that chipset yet, but support looks pretty good. Suspect it would work well as all M5 products do. Have played around with it a bit, but m5stack_core2  isn't as easy as m5stick. Get a few blowups getting audio to work with the unified libraries. Will continue to work with it, but might need some help with the bigger brains on the project. Have m5 stick plus, and m5 stack_core2 to work with at the moment for testing. Any help would be appreciated.

**Comment by rbergen** [comment]
@prschguy1 I just realized I completely missed this when you posted it. What kind of help would you need? (I don't want to claim ownership on the "bigger brains" moniker, but I think it will help me to understand the nature of the challenge better.)
