### ISSUE TITLE
Hang in ChangeEffect

### ISSUE THREAD

**Issue by davepl** [PlummersSoftwareLLC/NightDriverStrip#583]
Repro:

Start mesermizer
While "Mesmerizer" splash logo is visible, hit DOWN on the remote to decrement the effect

It then stops responding, and in the debugger I see the following:

(W) (IsEffectEnabled)(C1) Invalid index for IsEffectEnabled
(W) (IsEffectEnabled)(C1) Invalid index for IsEffectEnabled
(W) (IsEffectEnabled)(C1) Invalid index for IsEffectEnabled
(W) (IsEffectEnabled)(C1) Invalid index for IsEffectEnabled
(W) (IsEffectEnabled)(C1) Invalid index for IsEffectEnabled
(W) (IsEffectEnabled)(C1) Invalid index for IsEffectEnabled

**Comment by rbergen** [comment]
Yep, that's a bug, and I know what lines of code it is in. I'll open a PR with a fix later today.
