### ISSUE TITLE
New M5StickC Plus2 doesn't work

### ISSUE THREAD

**Issue by platini76** [PlummersSoftwareLLC/NightDriverStrip#618]
I tried to upload project as old M5stickc plus and did not work,
don't reach wifi config. someone has experience ?

**Comment by rbergen** [comment]
@platini76 Personally, I have no experience with the M5StickC Plus2. However, to narrow the field of investigation into what it is you're running into, it would be helpful if you could provide answers to the following questions:

1. Do I understand correctly that you are using the WebInstaller to upload the image?
2. What project/configuration are you trying to flash? I know the device you mentioned is the M5StickC Plus, but I'm not yet sure which of the projects that are available for that device.
3. Do you see any activity on the device's built-in LCD screen after the upload?

**Comment by rbergen** [comment]
As far as I'm aware, you **must** select a project before you can try to flash. This is the relevant section on the WebInstaller page:

![image](https://github.com/PlummersSoftwareLLC/NightDriverStrip/assets/10425218/edeea88c-18c8-4b97-af7b-ce42f53df735)

As you can see, you have to select a device in the first drop-down - I understand from your first message that you selected "M5StickC Plus" there, as shown in the picture. You then have to select a project in the second drop-down; if you don't the CONNECT button you have to push to start the flash doesn't even show underneath. So, my question is what project you selected there when you got stuck.

I can't really recommend a project without knowing what it is you are trying to do - i.e. what you are flashing the your M5StickC Plus2 for.

**Comment by platini76** [comment]
I select m5stick plus... it flashed... correctly, and when arrivate to next page... it say again ..... flash... dont recognize any flashed devices for wifi config

**Comment by rbergen** [comment]
Can you maybe provide screen shots of what you're seeing?

**Comment by platini76** [comment]
sure!

<img width="1370" alt="Screenshot 2024-04-09 alle 19 43 05" src="https://github.com/PlummersSoftwareLLC/NightDriverStrip/assets/10352902/3065cd31-0f0c-4566-b70a-1f30a1ae9797">
<img width="1360" alt="Screenshot 2024-04-09 alle 19 43 26" src="https://github.com/PlummersSoftwareLLC/NightDriverStrip/assets/10352902/d6cebcf6-346a-475e-a454-a19aaaa4e23e">
<img width="1275" alt="Screenshot 2024-04-09 alle 19 44 36" src="https://github.com/PlummersSoftwareLLC/NightDriverStrip/assets/10352902/45ceacf0-47f6-476f-a4fe-9d55cd497296">
<img width="1274" alt="Screenshot 2024-04-09 alle 19 46 00" src="https://github.com/PlummersSoftwareLLC/NightDriverStrip/assets/10352902/dfd311f2-699e-46ab-882f-2fe83d70d9cb">
<img width="1288" alt="Screenshot 2024-04-09 alle 19 46 25" src="https://github.com/PlummersSoftwareLLC/NightDriverStrip/assets/10352902/9bd7f505-8402-4b65-8fba-154b3ed2843d">
<img width="1210" alt="Screenshot 2024-04-09 alle 19 46 54" src="https://github.com/PlummersSoftwareLLC/NightDriverStrip/assets/10352902/71cd43e6-c113-4be6-b194-dd546e118114">

**Comment by rbergen** [comment]
Thank you, that's very helpful. Simply put, the last screenshot shows me that the M5StickC Plus2 isn't booting the image you flashed - or even trying to. I think this means the M5StickC Plus2 cannot be made to work using an image for a "plain" M5StickC Plus. Which means we'll have to wait for someone to add support for the Plus2 to the project.

**Comment by platini76** [comment]
thank you... hope someone will do it quickly...

**Comment by rbergen** [comment]
@platini76 I've done some more Googling about this, and it seems that the first hurdle is adding support for the M5StickC Plus2 to PlatformIO. There is an issue on their espressif32 project repo requesting exactly that: platformio/platform-espressif32#1346.

**Comment by rbergen** [comment]
@platini76 It turns out that @davepl found a way to add support for the Plus2 to NightDriverStrip without requiring "official" support in PlatformIO, and made the non-trivial effort required to apply the necessary changes to the codebase.

He discusses this in #641. As he also mentions, he has now added this support to his fork (at <https://github.com/davepl/NightDriverStrip>); you can pull and test the Plus2 support from there for now.

A merge of the relevant code into the main tree here will follow at a later time.
