### ISSUE TITLE
pio check complains about things we don't care about in libraries we don't control.

### ISSUE THREAD

**Issue by robertlipe** [PlummersSoftwareLLC/NightDriverStrip#622]
## Bug report
(Self-assigned: this is background for a PR I'll submit for review soon. I'll handle closing this.)

$ pio check -e demo
results in a load of warnings that we don't care about from a third party package, such as:

src/uzlib/src/tinfgzip.c:61: [low:style] The function 'uzlib_gzip_parse_header' is never used. [unusedFunction]
src/uzlib/src/tinflate.c:620: [low:style] Variable 'data' can be declared as pointer to const [constVariablePointer]
src/uzlib/src/tinflate.c:655: [low:style] Variable 'val' is assigned a value that is never used. [unreadVariable]
src/uzlib/src/tinflate.c:527: [low:style] The function 'uzlib_init' is never used. [unusedFunction]
src/uzlib/src/tinflate.c:541: [low:style] The function 'uzlib_uncompress_init' is never used. [unusedFunction]
src/uzlib/src/tinflate.c:617: [low:style] The function 'uzlib_uncompress_chksum' is never used. [unusedFunction]
src/uzlib/src/tinfzlib.c:41: [low:style] The function 'uzlib_zlib_parse_header' is never used. [unusedFunction]

**Problem**
Warnings are like roaches. If you get used to seeing 20, you don't mind seeing 21. If you're used to seeing 0, seeing 1 will appropriately catch your attention. We should see warnings only in code we reasonably control.

Ideally, we should see zero... and pio check would be fast enough to run as part of our presubmit, but it's so slow that's really not very practical. :-(

**Steps**

1.  pio check -e demo
2.  wait for totally too long ... because platformio and scons are slow - and single-threaded. Yet, it's not even cpu-bound. What the heck is it DOING all this time?
3.  observe warnings that we don't care about.

**Example**
100% reproducible with the above. Improved output that shows actual opportunities for improvement. (27 minutes!!?!?!)

rjlimac7 nightdriverstrip % pio check -e demo
*******************************************************************************************
Obsolete PIO Core v6.1.11 is used (previous was 6.1.13)
Please remove multiple PIO Cores from a system:
https://docs.platformio.org/en/latest/core/installation/troubleshooting.html
*******************************************************************************************
Checking demo > cppcheck (board: esp32dev; platform: platformio/espressif32@^6.3.0; framework: arduino)
-------------------------------------------------------------------------------------------
src/improv.cpp:113: [low:style] Consider using std::accumulate algorithm instead of a raw loop. [useStlAlgorithm]
src/improv.cpp:93: [low:style] The function 'build_rpc_response' is never used. [unusedFunction]
Error: cppcheck failed to perform check! Please examine tool output in verbose mode.
============================== [FAILED] Took 1649.54 seconds ==============================

Component     HIGH    MEDIUM    LOW
-----------  ------  --------  -----
src            0        0        2

Total          0        0        2

Environment    Tool      Status    Duration
-------------  --------  --------  ------------
demo           cppcheck  FAILED    00:27:29.543
========================== 1 failed, 0 succeeded in 00:27:29.543 ==============

Importantly, the noise is gone. The suggestion it makes is a good one because on S3 it will result in a vector addition. That's a much better signal:noise!

**Notes**
Once this ignore framework is in place, it should be intuitively obvious to even the most casual observer how to add additional suppressions in case we have warnings in other builds that show up in default.

**Comment by davepl** [comment]
I got the Windows shell down to zero warnings on /W4 /WX.  A worthy pursuit if done well…

- Dave
