### ISSUE TITLE
Build instructions should document requirements

### ISSUE THREAD

**Issue by robertlipe** [PlummersSoftwareLLC/NightDriverStrip#644]
I'm making this a bugreport because it'll probably take a few of us (esp. those that are multi-OS and have ability to make blank OS images for testing...) to produce a list of requirements.

## Bug report
New developers, following our instructions, can run into errors like this:

file:///NightDriverStrip-yulc/site/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Problem**

**Steps**

1.  Follow instructions.
2.  Observe build failure.
3.  Become sad. Start drinking.

**Example**
We should probably have a section of doc that lists requirements for installing
* Platformio
* (Does ESP-IDF have to be separately installed?)
* Vite
(any other npm kind of stuff?)

**Notes**
For MacOS, I know 'brew install vite' is the (a) solution to above.
Ideally, we'd have copy-pastable:
Linux: yum install platformio vite 
Windows: whatever
MacOS: recommend the excellent homebrew. $ brew install vite  Site for platformio, etc.

**Comment by rbergen** [comment]
I think the main thing is having a sufficiently current version of NodeJS and NPM installed (the latter being included with sufficiently current versions of the former). And yes, it does seem the Gods of NodeJS have, once again, changed the rules for doing that in a way that makes it mildly less obvious than it used to be, in recent-ish times. 

To be frank, I think this issue can be quite quickly addressed by a relatively modest change to the build tooling part of the README - more concretely by adding a reference to nodejs.org, and maybe urging the reader to follow the installation instructions published there with some care.

**Comment by rbergen** [comment]
One of the extremely annoying things about NodeJS is that the "current version" thing tends to be mission-critical, and the versions that get installed by "OS'es own" package managers (and I'll put Homebrew in that category, knowing full well that's not technically correct) tend to be far from current. So you'll end up with NodeJS without NPM, or versions of either/both that don't contain the "automatic dependency installation" cleverness that's only available in later versions.

That stuff can be maddening. So again, I agree making mention of this in the README would be a good idea, but I am also not sure how much hair-pulling it would _actually_ prevent. One really has to read such a mention with small print attention to not just (logically!) go "oh yeah, so I need NodeJS", run a "sudo apt install nodejs" and end up with a NodeJS version that works... but actually doesn't.

**Comment by rbergen** [comment]
I'll give it some more thought this weekend. I have a PR open that I intend to merge this weekend anyway, so I can easily add an update to README.md if I have a concrete piece of text to add/modify. Maybe it'll come to me, maybe it won't.

**Comment by rbergen** [comment]
I've updated the Build tools section in the README in relation to this in PR #643. I'll allow any interested reviewers another day to develop and voice an opinion on that PR, after which I will merge it.

**Comment by rbergen** [comment]
Thanks for the feedback! I've linked the PR to this issue, so the latter will get closed automatically when the former gets merged.
