### ISSUE TITLE
std::bad_alloc exception in Arduino OTA handler

### ISSUE THREAD

**Issue by laufersteppenwolf** [PlummersSoftwareLLC/NightDriverStrip#73]
## Bug report

**Problem**
The ESP32 repeatedly keeps on rebooting due to an unhandled exception (std::bad_alloc)
I don't know why exactly, but with the BROOKLYNROOM config, it happens the most.

The issue seems to be related to the Arduino OTA handler, see the stack trace below
src/main.cpp:674 relates to [this line](https://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/772a19ea361bc4f7c564d5504f82e55385b3d239/src/main.cpp#L674)

**Steps**

1.  build the BROOKLYNROOM config
2.  run the monitor
3.  catch the stacktrace

**Example**

**Notes**
Stack trace:
`
(I) (TerminateHandler)(C1) -------------------------------------------------------------------------------------
(I) (TerminateHandler)(C1) - NightDriverStrip Guru Meditation                              Unhandled Exception -
(I) (TerminateHandler)(C1) -------------------------------------------------------------------------------------
(I) (PrintOutputHeader)(C1) NightDriverStrip
(I)
(I) (PrintOutputHeader)(C1) -------------------------------------------------------------------------------------
(I) (PrintOutputHeader)(C1) M5STICKC: 0, USE_OLED: 1, USE_TFT: 0
(I) (PrintOutputHeader)(C1) Version 137: Wifi SSID: NETGEAR90 - ESP32 Free Memory: 68692, PSRAM:0, PSRAM Free: 0
(I) (PrintOutputHeader)(C1) ESP32 Clock Freq : 240 MHz
(I) (TerminateHandler)(C1) Terminated due to exception: std::bad_alloc

ELF file SHA256: 0000000000000000

Backtrace: 0x4008c84c:0x3ffb1e20 0x4008cac9:0x3ffb1e40 0x400dd3c9:0x3ffb1e60 0x4017f3f7:0x3ffb1e90 0x4017f45e:0x3ffb1eb0 0x4017e89b:0x3ffb1ed0 0x4017ee4e:0x3ffb1ef0 0x4017ea05:0x3ffb1f10 0x400e58dd:0x3ffb1f30 0x4010144e:0x3ffb1f70 0x400dd455:0x3ffb1f90 0x40104254:0x3ffb1fb0 0x4008db1a:0x3ffb1fd0
  #0  0x4008c84c:0x3ffb1e20 in invoke_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/panic.c:715
  #1  0x4008cac9:0x3ffb1e40 in abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/panic.c:715
  #2  0x400dd3c9:0x3ffb1e60 in TerminateHandler() at src/main.cpp:404
  #3  0x4017f3f7:0x3ffb1e90 in __cxxabiv1::__terminate(void (*)()) at /builds/idf/crosstool-NG/.build/src/gcc-5.2.0/libstdc++-v3/libsupc++/eh_terminate.cc:112
  #4  0x4017f45e:0x3ffb1eb0 in std::terminate() at /builds/idf/crosstool-NG/.build/src/gcc-5.2.0/libstdc++-v3/libsupc++/eh_terminate.cc:112
  #5  0x4017e89b:0x3ffb1ed0 in __cxa_throw at /builds/idf/crosstool-NG/.build/src/gcc-5.2.0/libstdc++-v3/libsupc++/eh_throw.cc:87
  #6  0x4017ee4e:0x3ffb1ef0 in operator new(unsigned int) at /builds/idf/crosstool-NG/.build/src/gcc-5.2.0/libstdc++-v3/libsupc++/new_op.cc:54
  #7  0x4017ea05:0x3ffb1f10 in operator new[](unsigned int) at /builds/idf/crosstool-NG/.build/src/gcc-5.2.0/libstdc++-v3/libsupc++/new_opv.cc:32
  #8  0x400e58dd:0x3ffb1f30 in WiFiUDP::parsePacket() at C:\Users\John Doe\.platformio\packages\framework-arduinoespressif32\cores\esp32/Udp.h:46
  #9  0x4010144e:0x3ffb1f70 in ArduinoOTAClass::handle() at C:\Users\John Doe\.platformio\packages\framework-arduinoespressif32\libraries\ArduinoOTA\src/ArduinoOTA.cpp:100
  #10 0x400dd455:0x3ffb1f90 in loop() at src/main.cpp:674
  #11 0x40104254:0x3ffb1fb0 in loopTask(void*) at C:\Users\John Doe\.platformio\packages\framework-arduinoespressif32\cores\esp32/main.cpp:23
  #12 0x4008db1a:0x3ffb1fd0 in vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
`

**Comment by rbergen** [comment]
I was wondering if anyone has reported this upstream, as in to the ArduinoOTA project?

**Comment by laufersteppenwolf** [comment]
> I was wondering if anyone has reported this upstream, as in to the ArduinoOTA project?

I have not. However, NightDriver uses this implementation: https://github.com/seanhagen/framework-arduinoespressif32
Which seems not really maintained

The "other" ArduinoOTA project is this one:  https://github.com/jandrassy/ArduinoOTA
Maybe it would be worth taking a look?

**Comment by rbergen** [comment]
> The "other" ArduinoOTA project is this one: https://github.com/jandrassy/ArduinoOTA
> Maybe it would be worth taking a look?

It sounds like it may well be. Obviously, it would require the involvement of at least someone with the hardware on which the issues at hand occur.

**Comment by BeldrothTheGold** [comment]
> > I was wondering if anyone has reported this upstream, as in to the ArduinoOTA project?
> 
> I have not. However, NightDriver uses this implementation: https://github.com/seanhagen/framework-arduinoespressif32 Which seems not really maintained
> 
> The "other" ArduinoOTA project is this one: https://github.com/jandrassy/ArduinoOTA Maybe it would be worth taking a look?

I don't think this is accurate. The platformio Espressif 32 platform comes with the espressif sponsored arduino-esp32 framework. (The version it comes with currently is 1.0.6) 

https://github.com/espressif/arduino-esp32/blob/1.0.6/libraries/ArduinoOTA/src/ArduinoOTA.h

**Comment by BeldrothTheGold** [comment]
I'm experimenting to see if this is fixed in the latest arduino-esp32 framework release 2.0.1. 
https://github.com/BeldrothTheGold/NightDriverStrip/tree/upstream-arduino

**Comment by BeldrothTheGold** [comment]
Updating to the latest arduino-esp32 framework release doesn't seem to resolve the issue with BROOKLYNROOM. This seems related to high RAM usage as I have been able to consistently upload the SPECTRUM project without issue. 

Once the available RAM gets below about 45k the project crashes during OTA upload.

**Comment by larryl79** [comment]
try download the code again/ update your code from main, since is updated already. I had a random crash before as well.

**Comment by rbergen** [comment]
Closing this as last issue update was over a year ago.
