### ISSUE TITLE
Unexpected behavior when effects are disabled via webserver

### ISSUE THREAD

**Issue by xcalibur839** [PlummersSoftwareLLC/NightDriverStrip#90]
## Bug report

**Problem**

- Disabling an effect that is currently running does not immediately stop the effect, it will continue to run until DEFAULT_EFFECT_INTERVAL has elapsed
- If you only have one effect in AllEffects[] and you disable that effect, the LEDs will appear to freeze in whatever their final state was after DEFAULT_EFFECT_INTERVAL has elapsed. This does not happen when there are multiple effects in AllEffects[] that are all disabled, due to the fading between effects that sets all LEDs to Off/Black (i.e. the final state of the LEDs is Off/Black)

**Steps**

1.  Enable the webserver and Wi-Fi in globals.h and configure secrets.h
2.  Determine the IP address of the ESP32 and connect to the webserver with a web browser
3.  Disable all of the listed effects (or call the /disableEffect endpoint using the curl example below on every effect)

**Example**

curl -d 'effectIndex=0' 192.168.0.25/disableEffect

**Comment by xcalibur839** [comment]
Working on [PR #93](https://github.com/PlummersSoftwareLLC/NightDriverStrip/pull/93) has changed my view on this issue. For example, clicking on a disabled effect from the web page will immediately play that effect even though it is disabled. However, it will not play automatically as part of the CheckEffectTimerExpired()/NextEffect() loop.

So perhaps the first part of this issue is not actually an issue, but is working as intended. Specifically:
> Disabling an effect that is currently running does not immediately stop the effect

The effect is still disabled as far as the EffectManager auto play is concerned.

**Comment by xcalibur839** [comment]
I think the biggest reason this behavior is unexpected is the lack of visual feedback for the currently running effect. When unchecking an effect in the list, there currently isn't any indication that unchecking the effect did anything until all of the effects are unchecked.

[PR #98](https://github.com/PlummersSoftwareLLC/NightDriverStrip/pull/98) attempts to address this issue by providing visual feedback that unchecking an effect did register, as well as the current timeframe for the actively running effect. This behavior is very similar to something like Windows Media Player, where the currently playing song is selected, a progress bar shows how much time is remaining, and the play queue can be modified without stopping playback of the current song.

**Comment by rbergen** [comment]
@xcalibur839 With #93 and #98 merged, I'm wondering what is left of this issue?

**Comment by xcalibur839** [comment]
@rbergen I think you're correct and this is no longer an issue! Closing now, thank you for everything!
